print("ez banned")
print("ez banned")
print("ez banned")
print("ez banned")
print("ez banned")
print("ez banned")
print("ez banned")
print("ez banned")
print("ez banned")
print("ez banned")
local player = game.Players.LocalPlayer
player:Kick("You've been banned for 69696969 DAYS. Reasons: Exploiting.")
